import './globals.css'
import Link from 'next/link'
import { LoginCom, LogoutCom } from './LoginCom'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html>
      <body>
        <nav>
          <Link href='/'><p>홈</p></Link>
          <Link href='/list'><p>문제</p></Link>
          <Link href='/new'><p>등록</p></Link>
          { session ? <LogoutCom/> : <LoginCom/>}
        </nav>
        {children}
        </body>
    </html>
  )
}


